### ISSUE TITLE
no method 'setPrototypeOf' in Node 0.10

### ISSUE THREAD

**Issue by phillipskevin** [feathersjs/feathers-errors#16]
Getting this error in Node 0.10 with feathers-errors 1.1.3.
```
> testee --browsers firefox viewer/test/index.html author/test/index.html
/home/travis/build/<project>/js/node_modules/testee/node_modules/feathers/node_modules/feathers-errors/lib/index.js:77
  Object.setPrototypeOf(AbstractError, klass);
         ^
TypeError: Object function Object() { [native code] } has no method 'setPrototypeOf'
    at AbstractError (/home/travis/build/<project>/js/node_modules/testee/node_modules/feathers/node_modules/feathers-errors/lib/index.js:77:10)
    at Object.<anonymous> (/home/travis/build/<project>/js/node_modules/testee/node_modules/feathers/node_modules/feathers-errors/lib/index.js:82:21)
```

**Comment by phillipskevin** [comment]
I see feathers-errors wants Node >= 0.12.

**Comment by ekryski** [comment]
Ya, unfortunately extending the Error object using ES6 classes is pretty hacky. If you really need v0.10 support let me know and we can re-open this issue. I can make it work but don't really want to since v0.10 is so many versions old already.
