### ISSUE TITLE
Possible issue with Node 4

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/feathers-errors#51]
I got the following while running tests for feathers-hooks-common on Node 4.

```
  3) validate DEPRECATED hooks validateUsingCallback test fails on errors:
     Uncaught ReferenceError: Reflect is not defined
      at BadRequest.ExtendableBuiltin (node_modules/feathers-errors/lib/index.js:21:20)
      at BadRequest.FeathersError (node_modules/feathers-errors/lib/index.js:99:87)
      at new BadRequest (node_modules/feathers-errors/lib/index.js:140:79)
      at cb (lib/common.js:317:64)
      at null._onTimeout (test/validate.test.js:47:15)
  4) validate DEPRECATED hooks validate Promise function test fails on errors:
     Uncaught ReferenceError: Reflect is not defined
      at BadRequest.ExtendableBuiltin (node_modules/feathers-errors/lib/index.js:21:20)
      at BadRequest.FeathersError (node_modules/feathers-errors/lib/index.js:99:87)
      at new BadRequest (node_modules/feathers-errors/lib/index.js:140:79)
      at null._onTimeout (test/validate.test.js:129:26)
```

Lines 316-318 are

```javascript
if (res && Object.keys(res).length) {
  throw new errors.BadRequest({ errors: res });
}
```

I required babel-polyfill and the problem didn't occur.

**Comment by eddyystop** [comment]
Feathers core requires babel-polyfill. So there's no problem with feathers-errors.
